apiVersion: v2
name: akamai-ml-operator
description: A Helm chart for AkamaiKnowledgeBase Kubernetes Operator
type: application
version: 0.1.0
appVersion: "0.1.0"
home: https://github.com/linode/ml-operator
sources:
  - https://github.com/linode/ml-operator/charts
