{{- if .Values.serviceAccount.allowedSecrets }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "pipelines.name" . }}-secret-reader
  namespace: {{ include "pipelines.namespace" . }}
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames:
    {{- range .Values.serviceAccount.allowedSecrets }}
      - {{ . | quote }}
    {{- end }}
    verbs: ["get", "list"]
{{- end }}
